
name: 部署文档

on:
  push:
    branches:
      # 确保这是你正在使用的分支名称
      # 在该分支发生push事件时触发
      - main

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true



      - name: 设置 Node.js
        uses: actions/setup-node@v3 # 作用：安装nodejs
        with:
          node-version: 16 # 版本
          cache: npm

      - name: 安装依赖
        run: npm install

      - name: 构建文档
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: npm run docs:build

      - name: 部署文档
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这是文档部署到的分支名称
          branch: master
          folder: docs/.vuepress/dist
